### ISSUE TITLE
"A kana recognition Anki deck with mnemonics" link can't be accessed

### ISSUE THREAD

**Issue by hiyorijl** [friedrich-de/AnimecardsWebsite#1]
the link for Anki cards [A kana recognition Anki deck with mnemonics](https://ankiweb.net/shared/info/2141155567) displayed on [Introduction to learning Japanese](https://animecards.site/learningjapanese/#1-first-steps) can't be accesed when I clicked on it it appears the following :

**No shared item found with provided id.**

could you fix it, please? 🙏

**Comment by CodeWithMa** [comment]
Use this instead: https://ankiweb.net/shared/info/1133476087

**Comment by hiyorijl** [comment]
Thanks, much appreciated!
