### ISSUE TITLE
Better filtering for Jitendex Dictionary?

### ISSUE THREAD

**Issue by snfergy** [friedrich-de/AnimecardsWebsite#9]
Hi, I was wondering if there was a way to better filter glossary terms with the Jitendex dictionary?
As it is right now it imports a lot of junk that doesn't really need to be on the card such as "See:" references, antonyms and example sentences.
The card example picture here has 18(!) definitions imported as a result.
![example2](https://github.com/friedrich-de/AnimecardsWebsite/assets/46796917/873dcee4-c819-4908-930f-1d9961d718d0)
![example1](https://github.com/friedrich-de/AnimecardsWebsite/assets/46796917/37fb51a4-f9fc-4c1c-9e7c-57e755cfbdd2)

**Comment by donkuri** [comment]
Sorry, how is this related to the Animecards website? If you want to change the appearance of Jitendex in Anki, probably [better to ask StephenMK directly](https://github.com/stephenmk/Jitendex).

**Comment by friedrich-de** [comment]
Probably related to this: https://github.com/friedrich-de/Basic-Mining-Deck
If you recreate the ticket there, I'll take a look later.
